version: '3.8'

services:
  reverse-proxy:
    image: nginx:mainline-alpine3.17
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  db:
    image: postgres:alpine3.18
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD="1234"
      - POSTGRES_USER=postgres
      - POSTGRES_DB=data
    volumes:
      - ./data:/var/lib/postgresql/data
  frontend:
    image: front
    ports:
      - 5000:5000
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:80
  backend:
    image: back
    ports:
      - 8080:8080
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD="1234"
      - POSTGRES_DATABASE=data
      - REQUEST_ORIGIN=http://127.0.0.1
    depends_on:
      - db
      - reverse-proxy
      - red
  red:
    image: redis

networks:
  default:
    name: std
