version: '3.8'

services:
  db:
    image: postgres:alpine3.18
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD="1234"
      - POSTGRES_USER=postgres
      - POSTGRES_DB=data
    volumes:
      - database:/var/lib/postgresql/data
  frontend:
    image: front
    ports:
      - 5000:5000
  backend:
    depends_on:
      - db
    image: back
    ports:
      - 8080:8080
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD="1234"
      - POSTGRES_DATABASE=data
    
  red:
    image: redis

volumes:
  database:
